CREATE TABLE SYS.CLASSINFO
(
    CLASSID NUMBER(2) PRIMARY KEY NOT NULL,
    CLASSNAME VARCHAR2(10) NOT NULL
);
COMMENT ON COLUMN SYS.CLASSINFO.CLASSID IS '主键ID';
COMMENT ON COLUMN SYS.CLASSINFO.CLASSNAME IS '姓名';